KILT-Foundation/sporran-extension

package.json
src/utilities/credentials/credentials.ts
src/utilities/did/did.ts
src/utilities/identities/identities.ts
src/views/IdentityCredentials/IdentityCredentials.test.tsx
src/views/SignQuote/SignQuote.test.tsx

SK-601: fix credential to DID matching

---

src/views/IdentityCredentials/IdentityCredentials.tsx
src/views/IdentityCredentials/__snapshots__/IdentityCredentials.test.tsx.snap

SK-640: open link in new tab

---

src/components/CredentialCard/CredentialCard.tsx
src/utilities/credentials/credentials.ts
src/views/IdentityCredentials/IdentityCredentials.test.tsx

SK-536: usePendingCredentialCheck

---

src/views/DidEndpointsForm/DidEndpointsForm.tsx
src/views/DidEndpointsForm/__snapshots__/DidEndpointsForm.test.tsx.snap

SK-639: fix link back on DID endpoint form

---

src/components/CopyValue/CopyValue.module.css
src/components/CopyValue/CopyValue.module.css.d.ts
src/components/CopyValue/CopyValue.stories.tsx
src/components/CopyValue/CopyValue.test.tsx
src/components/CopyValue/CopyValue.tsx
src/components/CopyValue/__snapshots__/CopyValue.test.tsx.snap
src/views/DidEndpointsForm/DidEndpointsForm.module.css
src/views/DidEndpointsForm/DidEndpointsForm.module.css.d.ts
src/views/DidEndpointsForm/DidEndpointsForm.test.tsx
src/views/DidEndpointsForm/DidEndpointsForm.tsx
src/views/DidEndpointsForm/__snapshots__/DidEndpointsForm.test.tsx.snap
src/views/DidEndpointsSign/DidEndpointsSign.module.css
src/views/DidEndpointsSign/DidEndpointsSign.module.css.d.ts
src/views/DidEndpointsSign/DidEndpointsSign.test.tsx
src/views/DidEndpointsSign/DidEndpointsSign.tsx
src/views/DidEndpointsSign/__snapshots__/DidEndpointsSign.test.tsx.snap
src/views/DidManage/DidManage.module.css
src/views/DidManage/DidManage.module.css.d.ts
src/views/DidManage/DidManage.test.tsx
src/views/DidManage/DidManage.tsx
src/views/DidManage/__snapshots__/DidManage.test.tsx.snap
src/views/ReceiveToken/ReceiveToken.module.css
src/views/ReceiveToken/ReceiveToken.module.css.d.ts
src/views/ReceiveToken/ReceiveToken.tsx
src/views/ReceiveToken/__snapshots__/ReceiveToken.test.tsx.snap
src/views/SignDApp/SignDApp.module.css
src/views/SignDApp/SignDApp.module.css.d.ts
src/views/SignDApp/SignDApp.tsx
src/views/SignDApp/__snapshots__/SignDApp.test.tsx.snap

SK-646: show managed DID

---

src/views/DidEndpointsForm/DidEndpointsForm.tsx
src/views/DidEndpointsForm/__snapshots__/DidEndpointsForm.test.tsx.snap

SK-639: again fix link back on DID endpoint form

---

src/__mocks__/webextension-polyfill-ts.ts
src/components/CredentialCard/CredentialCard.tsx
src/static/_locales/en/messages.json
src/utilities/credentials/CredentialsProvider.mock.tsx
src/views/SaveCredential/SaveCredential.module.css
src/views/SaveCredential/SaveCredential.module.css.d.ts
src/views/SaveCredential/SaveCredential.test.tsx
src/views/SaveCredential/SaveCredential.tsx
src/views/SaveCredential/__snapshots__/SaveCredential.test.tsx.snap

SK-647: backup credential view changes

---

.storybook/locales.jsx
src/views/SendToken/SendToken.tsx

SK-638: support more number separators

---

src/components/Settings/__snapshots__/Settings.test.tsx.snap
src/configuration/configuration.ts
src/static/manifest.json

SK-634: bump Sporran version

---

src/utilities/credentials/credentials.ts
src/views/SaveCredential/SaveCredential.tsx

SK-664: SaveCredential bugfix

---

package.json
src/utilities/identities/identities.ts
src/views/SignQuote/SignQuote.tsx
yarn.lock

SK-668 including a workaround for an SDK issue

SK-668: Bump @kiltprotocol/* from 0.24.1 to 0.24.2

---

src/backgroundScript.ts
src/contentScript.ts
src/dApps/SignRawChannels/backgroundSignRawChannel.ts
src/dApps/SignRawChannels/contentSignRawChannel.ts
src/dApps/SignRawChannels/injectedSignRawChannel.ts
src/dApps/SignerInjectedAPI/SignerInjectedAPI.ts
src/static/_locales/en/messages.json
src/utilities/popups/types.ts
src/views/PopupsRouter/PopupsRouter.tsx
src/views/SignRawDApp/SignRawDApp.module.css
src/views/SignRawDApp/SignRawDApp.module.css.d.ts
src/views/SignRawDApp/SignRawDApp.stories.tsx
src/views/SignRawDApp/SignRawDApp.test.tsx
src/views/SignRawDApp/SignRawDApp.tsx
src/views/SignRawDApp/__snapshots__/SignRawDApp.test.tsx.snap
src/views/paths.ts

SK-667: polkadot signRaw API

---

src/components/IdentitiesCarousel/IdentitiesCarousel.tsx
src/components/IdentitiesCarousel/__snapshots__/IdentitiesCarousel.test.tsx.snap
src/components/IdentitySlide/IdentitySlide.test.tsx
src/components/IdentitySlide/IdentitySlide.tsx
src/components/IdentitySlide/__snapshots__/IdentitySlide.test.tsx.snap
src/views/DidEndpointsForm/__snapshots__/DidEndpointsForm.test.tsx.snap
src/views/DidEndpointsSign/__snapshots__/DidEndpointsSign.test.tsx.snap
src/views/DidManage/__snapshots__/DidManage.test.tsx.snap
src/views/DidUpgrade/__snapshots__/DidUpgrade.test.tsx.snap
src/views/DidUpgradeExplainer/__snapshots__/DidUpgradeExplainer.test.tsx.snap
src/views/IdentityCredentials/__snapshots__/IdentityCredentials.test.tsx.snap
src/views/IdentityOverview/IdentityOverview.tsx
src/views/ReviewTransaction/__snapshots__/ReviewTransaction.test.tsx.snap
src/views/ShareCredentialSign/__snapshots__/ShareCredentialSign.test.tsx.snap
src/views/SignDid/__snapshots__/SignDid.test.tsx.snap
src/views/SignQuote/__snapshots__/SignQuote.test.tsx.snap

SK-675: Options menu only on IdentityOverview

---

src/components/CredentialCard/CredentialCard.test.tsx
src/components/CredentialCard/CredentialCard.tsx
src/components/CredentialCard/__snapshots__/CredentialCard.test.tsx.snap
src/views/DidDowngradeWarning/DidDowngradeWarning.tsx
src/views/SaveCredential/SaveCredential.tsx
src/views/SaveCredential/__snapshots__/SaveCredential.test.tsx.snap

remove credential card buttons on DID downgrade warning screen

---

src/utilities/credentials/credentials.ts
src/views/ImportCredentials/ImportCredentials.tsx

SK-344: fix import multiple credentials

---

src/views/DidDowngradeWarning/DidDowngradeWarning.tsx
src/views/DidDowngradeWarning/__snapshots__/DidDowngradeWarning.test.tsx.snap

SK-692: goBack on cancel

---

src/utilities/credentials/CredentialsContext.tsx
src/utilities/credentials/credentials.ts

SK-344: fix editing credentials

---

src/static/popup.html

SK-749: CSS charset

---

src/static/_locales/en/messages.json
src/utilities/plural/plural.test.ts
src/utilities/plural/plural.ts

SK-714: proper plurals locale

---

src/components/BalanceUpdateLink/BalanceUpdateLink.module.css

SK-115: Y no update

---

src/components/LinkBack/LinkBack.stories.tsx
src/components/LinkBack/LinkBack.test.tsx
src/components/LinkBack/LinkBack.tsx
src/components/LinkBack/__snapshots__/LinkBack.test.tsx.snap
src/static/_locales/en/messages.json
src/views/App/App.tsx
src/views/DidEndpointsFlow/DidEndpointsFlow.tsx
src/views/DidEndpointsForm/DidEndpointsForm.module.css
src/views/DidEndpointsForm/DidEndpointsForm.module.css.d.ts
src/views/DidEndpointsForm/DidEndpointsForm.stories.tsx
src/views/DidEndpointsForm/DidEndpointsForm.test.tsx
src/views/DidEndpointsForm/DidEndpointsForm.tsx
src/views/DidEndpointsForm/__snapshots__/DidEndpointsForm.test.tsx.snap
src/views/DidManage/DidManage.stories.tsx
src/views/DidManage/DidManage.test.tsx
src/views/DidManage/DidManage.tsx
src/views/DidManage/__snapshots__/DidManage.test.tsx.snap
src/views/paths.ts

SK-606: unsaved service endpoint

---

src/views/DidEndpointsForm/DidEndpointsForm.tsx

Prevent default submit

---

README.md
src/utilities/endpoints/endpoints.ts
src/views/AppSettings/__snapshots__/AppSettings.test.tsx.snap

SK-760: sporran-testnet endpoint

---

src/views/DidDowngradeWarning/DidDowngradeWarning.module.css

SK-716: changes to remove on-chain DID screen

---

src/views/App/App.tsx
src/views/IdentitiesRouter/IdentitiesRouter.tsx

SK-794: Bugfix - DID Update modal in unexpected places

---

src/static/_locales/en/messages.json
src/views/CreatePresentation/__snapshots__/CreatePresentation.test.tsx.snap

SK-718: credential presentation

---

src/components/Settings/__snapshots__/Settings.test.tsx.snap
src/configuration/configuration.ts
src/static/manifest.json
src/views/GenericError/__snapshots__/GenericError.test.tsx.snap

Also activates presentation feature in the public build

Version 2022.3.9

---

scripts/reimburseDids.js

Let's commit this so it is available for later use, e.g. to list how many DIDs are still affected.

add helper script for reimbursing DIDs

---

src/components/CredentialCard/PresentCredentialCard.tsx

SK-798: fix default presentation

---

src/components/CredentialCard/CredentialCard.module.css

SK-798: chrome scroll in dialog

---

src/views/DidDowngrade/DidDowngrade.tsx
src/views/DidEndpointsSign/DidEndpointsSign.tsx
src/views/DidRepair/DidRepair.tsx
src/views/DidUpgrade/DidUpgrade.tsx
src/views/UnlockVestedFunds/UnlockVestedFunds.tsx

SK-802: modal hides error

---

src/static/_locales/en/messages.json
src/views/W3NCreateForm/W3NCreateForm.tsx
src/views/W3NCreateForm/__snapshots__/W3NCreateForm.test.tsx.snap

SK-751: web3name dot

---

src/components/ExplainerModal/ExplainerModal.module.css
src/components/ExplainerModal/ExplainerModal.module.css.d.ts
src/components/ExplainerModal/ExplainerModal.stories.tsx
src/components/ExplainerModal/ExplainerModal.test.tsx
src/components/ExplainerModal/ExplainerModal.tsx
src/components/ExplainerModal/__snapshots__/ExplainerModal.test.tsx.snap
src/static/_locales/en/messages.json
src/views/DidUpgrade/DidUpgrade.module.css
src/views/DidUpgrade/DidUpgrade.module.css.d.ts
src/views/DidUpgrade/DidUpgrade.tsx
src/views/DidUpgrade/__snapshots__/DidUpgrade.test.tsx.snap
src/views/W3NCreateSign/W3NCreateSign.tsx
src/views/W3NCreateSign/__snapshots__/W3NCreateSign.test.tsx.snap

SK-866: deposit explainers

---

src/views/DidUpgradeExplainer/DidUpgradeExplainer.module.css
src/views/W3NCreateInfo/W3NCreateInfo.module.css

Checkbox border radius

---

src/static/_locales/en/messages.json
src/views/DidUpgradePromo/DidUpgradePromo.module.css
src/views/DidUpgradePromo/DidUpgradePromo.module.css.d.ts
src/views/DidUpgradePromo/DidUpgradePromo.tsx
src/views/DidUpgradePromo/__snapshots__/DidUpgradePromo.test.tsx.snap

SK-871: promo screens costs

---

src/utilities/did/did.ts

SK-867: fix DID resolve crash

---

src/static/_locales/en/messages.json
src/utilities/useWeb3Name/useWeb3Name.ts
src/views/IdentityOverview/IdentityOverview.module.css
src/views/IdentityOverview/IdentityOverview.module.css.d.ts
src/views/IdentityOverview/IdentityOverview.test.tsx
src/views/IdentityOverview/IdentityOverview.tsx
src/views/IdentityOverview/__snapshots__/IdentityOverview.test.tsx.snap

SK-772: web3name identity overview

---

package.json
yarn.lock

SK-898: Bump @kiltprotocol/* from 0.26.0 to 0.26.1

---

src/static/_locales/en/messages.json
src/views/W3NRemove/W3NRemove.test.tsx
src/views/W3NRemove/W3NRemove.tsx
src/views/W3NRemove/__snapshots__/W3NRemove.test.tsx.snap

SK-890: W3NRemove costs

---

src/components/CopyValue/CopyValue.module.css
src/views/DidManage/DidManage.module.css
src/views/DidManage/DidManage.tsx
src/views/DidManage/__snapshots__/DidManage.test.tsx.snap

SK-875: bigger icons

---

src/static/_locales/en/messages.json
src/testing/jest.setup.ts
src/views/DidDowngrade/DidDowngrade.stories.tsx
src/views/DidDowngrade/DidDowngrade.test.tsx
src/views/DidDowngrade/DidDowngrade.tsx
src/views/DidDowngrade/__snapshots__/DidDowngrade.test.tsx.snap
src/views/W3NRemove/W3NRemove.tsx

SK-901: Update costs for removing promo on-chain DID

---

src/static/_locales/en/messages.json
src/utilities/extrinsicDetails/extrinsicDetails.ts
src/views/SignDApp/SignDApp.module.css
src/views/SignDApp/SignDApp.module.css.d.ts
src/views/SignDApp/SignDApp.tsx
src/views/SignDApp/useExtrinsicValues.ts
src/views/SignDidExtrinsic/SignDidExtrinsic.module.css
src/views/SignDidExtrinsic/SignDidExtrinsic.module.css.d.ts
src/views/SignDidExtrinsic/SignDidExtrinsic.tsx
src/views/SignDidExtrinsic/useExtrinsicValues.ts

SK-846: nicer extrinsic details

---

src/utilities/endpoints/endpoints.ts

SK-911: Default endpoint Peregrine

---

src/components/LegacyDids/LegacyDids.tsx
src/utilities/useBooleanState/useBooleanState.ts

SK-804: stable boolean state

---

src/components/AddIdentity/__snapshots__/AddIdentity.test.tsx.snap
src/static/_locales/en/messages.json

SK-797: add identity

---

src/views/W3NRemove/W3NRemove.tsx

SK-912: Fix w3n removal deposit bug

---

src/configuration/configuration.ts
src/views/SendToken/SendToken.tsx
src/views/SendToken/__snapshots__/SendToken.test.tsx.snap

SK-788: recipient dropdown

---

src/utilities/endpoints/endpoints.ts
src/utilities/promoBackend/promoBackend.ts
src/utilities/useSubscanHost/useSubscanHost.ts
src/views/AppSettings/__snapshots__/AppSettings.test.tsx.snap

SK-928
Bringing in the changes made for the https://github.com/BTE-Trusted-Entity/sporran-extension/releases/tag/v2022.4.12 release

SK-928: dwellir

---

src/utilities/endpoints/endpoints.ts
src/utilities/promoBackend/promoBackend.ts
src/utilities/useSubscanHost/useSubscanHost.ts

SK-874: endpoints dependencies

---

src/views/DidEndpointsFlow/DidEndpointsFlow.tsx

SK-832: back to flow

---

src/components/CredentialCard/CredentialCard.tsx
src/components/CredentialCard/ShareCredentialCard.tsx
src/views/IdentityCredentials/IdentityCredentials.stories.tsx

SK-765: useScrollIntoView changes

---

src/views/W3NCreateFlow/W3NCreateFlow.tsx
src/views/W3NCreateForm/W3NCreateForm.stories.tsx
src/views/W3NCreateForm/W3NCreateForm.test.tsx
src/views/W3NCreateForm/W3NCreateForm.tsx
src/views/W3NCreateForm/__snapshots__/W3NCreateForm.test.tsx.snap
src/views/W3NCreateInfo/W3NCreateInfo.stories.tsx
src/views/W3NCreateInfo/W3NCreateInfo.test.tsx
src/views/W3NCreateInfo/W3NCreateInfo.tsx
src/views/W3NCreateInfo/__snapshots__/W3NCreateInfo.test.tsx.snap
src/views/W3NCreatePromo/W3NCreatePromo.stories.tsx
src/views/W3NCreatePromo/W3NCreatePromo.test.tsx
src/views/W3NCreatePromo/W3NCreatePromo.tsx
src/views/W3NCreateSign/W3NCreateSign.stories.tsx
src/views/W3NCreateSign/W3NCreateSign.test.tsx
src/views/W3NCreateSign/W3NCreateSign.tsx
src/views/paths.ts

SK-915: Bugfix - promo state reset on navigation

---

src/static/_locales/en/messages.json
src/utilities/did/useIsOnChainDidDeleted.ts
src/views/DidUpgradeExplainer/DidUpgradeExplainer.test.tsx
src/views/DidUpgradeExplainer/DidUpgradeExplainer.tsx
src/views/IdentityOverview/IdentityOverview.test.tsx
src/views/IdentityOverview/IdentityOverview.tsx
src/views/SignQuote/SignQuote.module.css
src/views/SignQuote/SignQuote.module.css.d.ts
src/views/SignQuote/SignQuote.stories.tsx
src/views/SignQuote/SignQuote.test.tsx
src/views/SignQuote/SignQuote.tsx
src/views/SignQuote/__snapshots__/SignQuote.test.tsx.snap

SK-776: Show error when on-chain DID deleted

---

src/static/_locales/en/messages.json
src/views/DidEndpointsForm/DidEndpointsForm.module.css
src/views/DidEndpointsForm/DidEndpointsForm.module.css.d.ts
src/views/DidEndpointsForm/DidEndpointsForm.tsx

SK-801: service endpoints limits 2

---

src/utilities/did/useIsOnChainDidDeleted.ts

SK-973: safe did deletion check

---

src/components/Card/Card.module.css
src/static/_locales/en/messages.json
src/views/IdentityCredentials/IdentityCredentials.module.css
src/views/IdentityCredentials/IdentityCredentials.module.css.d.ts
src/views/IdentityCredentials/IdentityCredentials.tsx
src/views/IdentityCredentials/__snapshots__/IdentityCredentials.test.tsx.snap

SK-743: Import credentials entry point

---

src/components/View/View.module.css

SK-1040: Fix background overflow

---

src/views/DidManage/DidManage.module.css
src/views/DidManage/DidManage.module.css.d.ts
src/views/DidManage/DidManage.tsx
src/views/DidManage/__snapshots__/DidManage.test.tsx.snap
src/views/W3NManage/W3NManage.module.css
src/views/W3NManage/W3NManage.module.css.d.ts
src/views/W3NManage/W3NManage.tsx
src/views/W3NManage/__snapshots__/W3NManage.test.tsx.snap

SK-1055: Remove subheadings on manage screens

---

src/static/_locales/en/messages.json
src/views/DidUpgradeExplainer/DidUpgradeExplainer.module.css
src/views/DidUpgradeExplainer/DidUpgradeExplainer.module.css.d.ts
src/views/DidUpgradeExplainer/DidUpgradeExplainer.test.tsx
src/views/DidUpgradeExplainer/DidUpgradeExplainer.tsx
src/views/DidUpgradeExplainer/__snapshots__/DidUpgradeExplainer.test.tsx.snap

SK-914: Show Removed DID

---

src/utilities/useSubmitStates/useSubmitStates.ts

SK-1090: vesting fees check

---

src/utilities/transformBalances/transformBalances.ts

SK-1089: locks cause negative balance

---

src/views/DidUpgradeExplainer/DidUpgradeExplainer.tsx

SK-1053: did removed flickering

---

src/__mocks__/webextension-polyfill-ts.ts
src/views/ExternalAccess/ExternalAccess.module.css
src/views/ExternalAccess/ExternalAccess.module.css.d.ts
src/views/ExternalAccess/ExternalAccess.tsx
src/views/ExternalAccess/__snapshots__/ExternalAccess.test.tsx.snap

SK-1058: Handle Long URLs on website access screen

---

src/components/Settings/__snapshots__/Settings.test.tsx.snap
src/configuration/configuration.ts
src/static/manifest.json
src/views/GenericError/__snapshots__/GenericError.test.tsx.snap

SK-1173: Version 2022.7.11

---

src/components/TxStatusModal/TxStatusModal.module.css
src/components/TxStatusModal/TxStatusModal.module.css.d.ts
src/components/TxStatusModal/TxStatusModal.tsx
src/components/TxStatusModal/__snapshots__/TxStatusModal.test.tsx.snap
src/static/_locales/en/messages.json

SK-1263: Error status for migration

---

src/channels/CreateDidChannels/types.ts
src/injectedScript.ts
src/static/_locales/en/messages.json
src/utilities/identities/IdentitiesProvider.mock.tsx
src/views/CreateDidDApp/CreateDidDApp.stories.tsx
src/views/CreateDidDApp/CreateDidDApp.test.tsx
src/views/CreateDidDApp/CreateDidDApp.tsx
src/views/CreateDidDApp/__snapshots__/CreateDidDApp.test.tsx.snap

SK-1297: Submitter parameter

---

src/static/_locales/en/messages.json
src/views/W3NCreateForm/W3NCreateForm.tsx

SK-1326: w3n capital letter error message

---

src/views/SendToken/SendToken.tsx

SK-1381: Send All needs to be clicked twice

---

src/views/ImportCredentials/ImportCredentials.module.css
src/views/ImportCredentials/ImportCredentials.tsx
src/views/ImportCredentials/ImportCredentialsForm.tsx
src/views/ImportCredentials/ImportCredentialsResults.tsx

SK-1098: import results accept more

---

src/components/Settings/__snapshots__/Settings.test.tsx.snap
src/configuration/configuration.ts
src/static/manifest.json
src/views/GenericError/__snapshots__/GenericError.test.tsx.snap

Version 2022.10.11

---

src/components/CredentialCard/CredentialCard.tsx
src/static/_locales/en/messages.json

SK-1337: new text for deleting revoked credential

---

src/components/CredentialCard/CredentialCard.test.tsx
src/components/CredentialCard/ShareCredentialCard.stories.tsx
src/components/CredentialCard/ShareCredentialCard.tsx
src/components/CredentialCard/__snapshots__/CredentialCard.test.tsx.snap
src/views/ShareCredentialSelect/ShareCredentialSelect.tsx
src/views/ShareCredentialSelect/__snapshots__/ShareCredentialSelect.test.tsx.snap

SK-1378: Select and expand last credential when there are few

---

src/components/CredentialCard/CredentialCard.tsx
src/static/_locales/en/messages.json
src/utilities/credentials/credentials.ts
src/utilities/did/did.ts
src/utilities/did/useIsOnChainDidDeleted.ts
src/utilities/didDowngrade/didDowngrade.ts
src/utilities/didUpgrade/didUpgrade.ts
src/utilities/getDeposit/getDeposit.ts
src/utilities/identities/identities.ts
src/utilities/identities/types.ts
src/utilities/useWeb3Name/useWeb3Name.ts
src/views/CreatePresentation/CreatePresentation.tsx
src/views/DidDowngrade/DidDowngrade.tsx
src/views/DidEndpointsForm/DidEndpointsForm.tsx
src/views/DidEndpointsSign/DidEndpointsSign.tsx
src/views/DidManage/DidManage.tsx
src/views/DidRepair/DidRepair.tsx
src/views/DidUpgrade/DidUpgrade.tsx
src/views/DidUpgradeExplainer/DidUpgradeExplainer.tsx
src/views/IdentityOverview/IdentityOverview.tsx
src/views/ImportCredentials/ImportCredentials.tsx
src/views/ShareCredentialSelect/ShareCredentialSelect.tsx
src/views/SignDidExtrinsic/SignDidExtrinsic.tsx
src/views/SignDidExtrinsic/didExtrinsic.ts
src/views/SignQuote/SignQuote.tsx
src/views/W3NCreateForm/W3NCreateForm.tsx
src/views/W3NCreateInfo/W3NCreateInfo.tsx
src/views/W3NCreateSign/W3NCreateSign.tsx
src/views/W3NManage/W3NManage.tsx
src/views/W3NRemove/W3NRemove.tsx

SK-1431: optional identity.did

---

src/utilities/didDowngrade/didDowngrade.ts

SK-1431: simpler batching

---

src/views/DidManage/DidManage.module.css
src/views/IdentityOverview/IdentityOverview.module.css

SK-1499: remove "new" pennant

---

src/utilities/useTXDSubmitter/useTXDSubmitter.ts

SK-1577: Use TXD Dev

---

src/components/Settings/__snapshots__/Settings.test.tsx.snap
src/configuration/configuration.ts
src/static/manifest.json
src/views/GenericError/__snapshots__/GenericError.test.tsx.snap

SK-1570: Version 2022.12.15

---

src/configuration/configuration.ts
src/utilities/didDowngrade/didDowngrade.ts
src/utilities/didRepair/didRepair.ts
src/utilities/didUpgrade/didUpgrade.ts
src/utilities/initKiltSDK/initKiltSDK.ts
src/utilities/transfers/transfers.ts
src/utilities/useSubmitStates/useSubmitStates.ts

SK-1431: default resolveOn

---

src/utilities/initKiltSDK/ApiProvider.tsx
src/views/App/App.tsx
src/views/ExternalAccess/ExternalAccess.tsx
src/views/ExternalAccess/__snapshots__/ExternalAccess.test.tsx.snap

SK-1584: restore access to settings before the blockchain connection

---

src/views/SendToken/SendToken.test.tsx
src/views/SendToken/SendToken.tsx

SK-1572: fix too many decimal places

---

src/views/App/App.tsx

SK-1584: fix SignDidExtrinsic popup

---

src/components/Settings/__snapshots__/Settings.test.tsx.snap
src/configuration/configuration.ts
src/static/manifest.json
src/views/GenericError/__snapshots__/GenericError.test.tsx.snap

SK-1593: Version 2022.12.13

---

src/views/DidEndpointsForm/DidEndpointsForm.test.tsx
src/views/DidEndpointsForm/DidEndpointsForm.tsx
src/views/DidEndpointsForm/__snapshots__/DidEndpointsForm.test.tsx.snap

SK-1601: expand "add service" by default

---

package.json

https://github.com/storybookjs/storybook/issues/19692

Storybook workaround Node 18

---

src/utilities/identities/IdentitiesProvider.mock.tsx
src/utilities/identities/identities.ts
src/utilities/identities/types.ts
src/views/CreateDidDApp/__snapshots__/CreateDidDApp.test.tsx.snap
src/views/DidDowngrade/DidDowngrade.tsx
src/views/DidUpgradeExplainer/DidUpgradeExplainer.tsx

SK-1602: show removed DID

---

src/utilities/identities/identities.ts

SK-1602
With Peregrine being down then I could not find out that for a deactivated DID the canonicalId is not returned. Makes things a bit wordier.

SK-1602: show removed DID fix

---

src/utilities/credentials/credentials.ts
src/views/SignDid/SignDid.tsx

SK-1614
[SK-1614]: https://kiltprotocol.atlassian.net/browse/SK-1614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SK-1614: fix credential selective disclosure 

---

src/configuration/configuration.ts
src/views/DidUpgradeExplainer/__snapshots__/DidUpgradeExplainer.test.tsx.snap

SK-1630: enable checkout

---

src/utilities/credentials/credentials.ts
src/utilities/endpoints/endpoints.ts
src/views/DidEndpointsForm/DidEndpointsForm.tsx
src/views/DidEndpointsForm/__snapshots__/DidEndpointsForm.test.tsx.snap

SK-1509: Presentation as collection

---

package.json
src/utilities/useInterval/useInterval.test.ts
src/views/W3NCreateSign/W3NCreateSign.tsx
src/views/W3NCreateSign/__snapshots__/W3NCreateSign.test.tsx.snap
yarn.lock

SK-1647
I also noticed a console warning in tests and fixed it

SK-1647: no w3n without coins

---

src/views/W3NCreateSignEuro/W3NCreateSignEuro.tsx

SK-1615: include address in Checkout URL

---

src/static/_locales/en/messages.json
src/views/ShareCredentialSign/ShareCredentialSign.tsx

SK-1338: Check Credential status when sharing

---

LICENSE
src/static/LICENSE.KILTprotocol.txt
src/static/_locales/en/messages.json

SK-1664: update license

---

src/components/UnknownIdentity/UnknownIdentity.module.css
src/components/UnknownIdentity/UnknownIdentity.module.css.d.ts
src/components/UnknownIdentity/UnknownIdentity.stories.tsx
src/components/UnknownIdentity/UnknownIdentity.test.tsx
src/components/UnknownIdentity/UnknownIdentity.tsx
src/components/UnknownIdentity/__snapshots__/UnknownIdentity.test.tsx.snap
src/static/_locales/en/messages.json
src/views/SignDApp/SignDApp.stories.tsx
src/views/SignDApp/SignDApp.tsx
src/views/SignRawDApp/SignRawDApp.stories.tsx
src/views/SignRawDApp/SignRawDApp.tsx

SK-1044: handle unknown identity

---

src/views/DidUpgradeEuro/DidUpgradeEuro.tsx
src/views/DidUpgradeEuro/__snapshots__/DidUpgradeEuro.test.tsx.snap

SK-1438: remove method from DID upgrade

---

src/utilities/credentials/credentials.ts

SK-1676: Check status button works for pending credentials

---

src/channels/SignDidExtrinsicChannels/types.ts
src/injectedScript.ts
src/utilities/identities/identities.ts
src/views/SignDidExtrinsic/SignDidExtrinsic.stories.tsx
src/views/SignDidExtrinsic/SignDidExtrinsic.test.tsx
src/views/SignDidExtrinsic/SignDidExtrinsic.tsx
src/views/SignDidExtrinsic/__snapshots__/SignDidExtrinsic.test.tsx.snap
yarn.lock

SK-1575: Burner Key

---

LICENSE

SK-1664: Sporran is still BTE

---

src/components/Settings/__snapshots__/Settings.test.tsx.snap
src/configuration/configuration.ts
src/static/manifest.json
src/views/GenericError/__snapshots__/GenericError.test.tsx.snap

SK-1690: Version 2023.2.16

---

src/views/ShareCredentialSign/ShareCredentialSign.module.css
src/views/ShareCredentialSign/ShareCredentialSign.tsx
src/views/ShareCredentialSign/__snapshots__/ShareCredentialSign.test.tsx.snap

SK-1338: Fix tooltip position

---

src/views/DidUpgradeExplainer/DidUpgradeExplainer.test.tsx
src/views/W3NCreateSignEuro/W3NCreateSignEuro.tsx

https://github.com/KILTprotocol/ticket/issues/2485

No address for web3name checkout

---

src/views/DidUpgradeExplainer/DidUpgradeExplainer.module.css

https://github.com/KILTprotocol/ticket/issues/2547

Remove padding to make long text fit

---

src/components/PasswordField/PasswordField.test.tsx
src/components/PasswordField/PasswordField.tsx
src/static/_locales/en/messages.json
src/views/ShareCredentialSign/ShareCredentialSign.tsx
src/views/ShareCredentialSign/__snapshots__/ShareCredentialSign.test.tsx.snap
src/views/SignQuote/SignQuote.tsx
src/views/SignQuote/__snapshots__/SignQuote.test.tsx.snap

KILTprotocol/ticket/issues/2622

support password autofilling

---

src/components/LegacyDids/__snapshots__/LegacyDids.test.tsx.snap
src/static/_locales/en/messages.json
src/views/DidDowngrade/__snapshots__/DidDowngrade.test.tsx.snap
src/views/DidDowngradeWarningCredentials/__snapshots__/DidDowngradeWarningCredentials.test.tsx.snap
src/views/DidDowngradeWarningWeb3Name/__snapshots__/DidDowngradeWarningWeb3Name.test.tsx.snap
src/views/DidManage/__snapshots__/DidManage.test.tsx.snap
src/views/DidRepair/__snapshots__/DidRepair.test.tsx.snap
src/views/DidUpgrade/__snapshots__/DidUpgrade.test.tsx.snap
src/views/DidUpgradeEuro/__snapshots__/DidUpgradeEuro.test.tsx.snap
src/views/DidUpgradeExplainer/__snapshots__/DidUpgradeExplainer.test.tsx.snap
src/views/IdentityOverview/__snapshots__/IdentityOverview.test.tsx.snap
src/views/SignDid/__snapshots__/SignDid.test.tsx.snap
src/views/SignDidExtrinsic/__snapshots__/SignDidExtrinsic.test.tsx.snap
src/views/SignDidStart/__snapshots__/SignDidStart.test.tsx.snap
src/views/W3NCreateInfo/__snapshots__/W3NCreateInfo.test.tsx.snap
src/views/W3NCreateSign/__snapshots__/W3NCreateSign.test.tsx.snap

https://github.com/KILTprotocol/ticket/issues/2630

Text changes

---

src/components/PasswordField/PasswordField.tsx

KILTprotocol/ticket/issues/2622

support password autofilling v2

---

src/views/IdentityCredentials/IdentityCredentials.module.css
src/views/IdentityCredentials/IdentityCredentials.tsx

https://github.com/KILTprotocol/ticket/issues/2609

minimal animation duration

---

src/static/_locales/en/messages.json
src/views/CreateDidDApp/__snapshots__/CreateDidDApp.test.tsx.snap
src/views/DidRepair/__snapshots__/DidRepair.test.tsx.snap
src/views/IdentityOverview/__snapshots__/IdentityOverview.test.tsx.snap
src/views/SignQuote/__snapshots__/SignQuote.test.tsx.snap

https://github.com/KILTprotocol/ticket/issues/2641

2641: Regression test fixes

---

package.json
src/utilities/exceptionToJson/exceptionToJson.ts
src/views/ShareCredentialSelect/ShareCredentialSelect.tsx
src/views/ShareCredentialSelect/__snapshots__/ShareCredentialSelect.test.tsx.snap

Fixes https://github.com/KILTprotocol/ticket/issues/2612

show revoked credentials

---

src/static/_locales/en/messages.json
src/views/DidEndpointsForm/DidEndpointsForm.tsx

https://github.com/KILTprotocol/ticket/issues/2662

relax service ID validation

---

src/channels/CredentialChannels/backgroundCredentialChannel.ts
src/static/_locales/en/messages.json
src/utilities/identities/identities.ts
src/views/SignQuote/SignQuote.test.tsx
src/views/SignQuote/SignQuote.tsx
src/views/SignQuote/__snapshots__/SignQuote.test.tsx.snap

https://github.com/KILTprotocol/ticket/issues/2627

claim determines owner DID

---

src/components/CredentialCard/CredentialCard.module.css
src/components/CredentialCard/CredentialCard.module.css.d.ts
src/components/CredentialCard/PresentCredentialCard.tsx
src/components/CredentialCard/ShareCredentialCard.tsx
src/components/CredentialCard/SignDidCredentialCard.tsx
src/static/_locales/en/messages.json
src/views/ShareCredentialSelect/ShareCredentialSelect.module.css
src/views/ShareCredentialSelect/ShareCredentialSelect.module.css.d.ts
src/views/ShareCredentialSelect/ShareCredentialSelect.stories.tsx
src/views/ShareCredentialSelect/ShareCredentialSelect.tsx
src/views/ShareCredentialSelect/__snapshots__/ShareCredentialSelect.test.tsx.snap
src/views/ShareCredentialSign/ShareCredentialSign.tsx
src/views/SignDidCredentialsSelect/__snapshots__/SignDidCredentialsSelect.test.tsx.snap

https://github.com/KILTprotocol/ticket/issues/2663

Allow sharing revoked credentials with verifier

---

src/utilities/credentials/credentials.ts
src/views/ShareCredentialSign/ShareCredentialSign.tsx

https://github.com/KILTprotocol/ticket/issues/2676

Handle removed attestations

---

src/utilities/endpoints/endpoints.ts
src/utilities/initKiltSDK/initKiltSDK.ts
src/views/AppSettings/AppSettings.tsx

The internal version allows the developers to specify any custom endpoint

permissive endpoints

---

src/popupScript.tsx
src/utilities/checkTestEnvironment/checkTestEnvironment.ts
src/views/App/App.module.css
src/views/App/App.module.css.d.ts
src/views/App/App.tsx

https://github.com/KILTprotocol/ticket/issues/2756
https://github.com/KILTprotocol/ticket/issues/2755

test environment

---

docs/external.md

https://github.com/KILTprotocol/ticket/issues/2793

simpler external installation

---

src/utilities/getDeposit/getDeposit.ts
src/views/DidEndpointsSign/DidEndpointsSign.tsx

https://github.com/KILTprotocol/ticket/issues/2790

new DID deposits

---

src/views/ShareCredentialSelect/ShareCredentialSelect.tsx

Fixes https://github.com/KILTprotocol/ticket/issues/2864

filter credentials by owner

---

src/utilities/getDeposit/getDeposit.ts
src/views/DidEndpointsSign/DidEndpointsSign.test.tsx
src/views/DidEndpointsSign/DidEndpointsSign.tsx
src/views/DidEndpointsSign/__snapshots__/DidEndpointsSign.test.tsx.snap

https://github.com/KILTprotocol/ticket/issues/2925

Bugfix: Insufficient balance message does not match costs

---

renovate.json

Resolves https://github.com/KILTprotocol/ticket/issues/2931

Reorder package rules

---

src/utilities/checkout/checkout.ts
src/utilities/endpoints/endpoints.ts
src/utilities/useSubscanHost/useSubscanHost.ts
src/views/AppSettings/__snapshots__/AppSettings.test.tsx.snap

Replace IBP RPC endpoints fixes https://github.com/KILTprotocol/ticket/issues/3505

chore: replace IBP rpc endpoints

---

src/channels/toggleIconChannel/toggleIconChannel.ts
src/components/Settings/__snapshots__/Settings.test.tsx.snap
src/configuration/configuration.ts
src/static/manifest.json
src/utilities/base64/base64.ts
src/utilities/storageEncryption/storageEncryption.ts
src/views/GenericError/__snapshots__/GenericError.test.tsx.snap

Fixing the manifest file as per Toms old PR and branch

fix: manifest v3

---

package.json
src/dApps/injectIntoDApp/injectIntoDApp.ts
src/utilities/balanceChanges/balanceChanges.test.ts
src/utilities/getDeposit/getDeposit.ts
yarn.lock

Fixes interaction with the new peregrine runtime.

chore: upgrade to sdk rc (v0)

---

LICENSE
src/components/CredentialCard/CredentialCard.tsx
src/components/Settings/Settings.tsx
src/components/Settings/__snapshots__/Settings.test.tsx.snap
src/static/LICENSE.KILTprotocol.txt
src/static/_locales/en/messages.json
src/utilities/endpoints/endpoints.ts
src/views/AppSettings/__snapshots__/AppSettings.test.tsx.snap
src/views/DidManage/DidManage.tsx
src/views/DidManage/__snapshots__/DidManage.test.tsx.snap

Updating to the KILT Foundation

chore: change license to kilt foundation

---

src/components/Settings/__snapshots__/Settings.test.tsx.snap
src/configuration/configuration.ts
src/static/manifest.json
src/views/GenericError/__snapshots__/GenericError.test.tsx.snap

chore: set version
